spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${DB}://${HOST}:${PORT}/${NAME}?createDatabaseIfNotExist=true
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL-AUTO}
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  mail:
    # host, port는 naver에서 정해준 값
    host: smtp.naver.com
    port: 465
    # 본인 naver 계정정보 삽입
    username: ${NAVER-MAIL-ID}
    password: ${NAVER-MAIL-PASSWORD}
    # 전송하기 위한 prop으로 ssl의 신뢰, 권한 등 사용허가
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com