spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:${DB}://${HOST}:${PORT}/${NAME}?createDatabaseIfNotExist=true
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL-AUTO}
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

jwt:
  header: ${HEADER_STRING}
  access-token-secret: ${ACCESS_TOKEN_SECRET}
  access-token-validity-in-seconds: ${ACCESS_TOKEN_EXPIRE}
  refresh-token-secret: ${REFRESH_TOKEN_SECRET}
  refresh-token-validity-in-seconds: ${REFRESH_TOKEN_EXPIRE}