spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: jdbc:${DB}://${HOST}:${PORT}/${NAME}?createDatabaseIfNotExist=true
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL-AUTO}
    database-platform: ${DIALECT}
    properties:
      hibernate:
        jdbc:
          time_zone: ${TIME_ZONE}
app:
  mail:
    protocol: ${MAIL_PROTOCOL}
    value: ${MAIL_VALUE}
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
  jwt:
    header: ${SECRET_HEADER}
    access_token_secret: ${ACCESS_TOKEN_SECRET}
    access_token_validity_in_seconds: ${ACCESS_TOKEN_VALIDITY_IN_SECONDS}
    refresh_token_secret: ${REFRESH_TOKEN_SECRET}
    refresh_token_validity_in_seconds: ${REFRESH_TOKEN_VALIDITY_IN_SECONDS}