spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/moasis?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  header: Authorization
  secret: cnV0eXdlb3JpdHV3eWVyb3RpdXdleXJ0b2l1d2V5cnRvd2VpdXJ0eXdhaXNkamZvaWF6eGNpdm5xd2Vpb2lhZHNmCg==
  access-token-validity-in-seconds: 600 # 10 min