spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: jdbc:${DB}://${HOST}:${PORT}/${NAME}?createDatabaseIfNotExist=true
    username: ${USER}
    password: ${PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL-AUTO}
    database-platform: ${DIALECT}
    properties:
      hibernate:
        jdbc:
          time_zone: ${TIME_ZONE}

  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: name, email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${NAVER_REDIRECT_URI}

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            scope: profile_nickname, account_email
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-authentication-method: POST

app:
  mail:
    protocol: ${MAIL_PROTOCOL}
    value: ${MAIL_VALUE}
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
  jwt:
    header: ${SECRET_HEADER}
    access_token_secret: ${ACCESS_TOKEN_SECRET}
    access_token_validity_in_seconds: ${ACCESS_TOKEN_VALIDITY_IN_SECONDS}
    refresh_token_secret: ${REFRESH_TOKEN_SECRET}
    refresh_token_validity_in_seconds: ${REFRESH_TOKEN_VALIDITY_IN_SECONDS}